# Generated by Django 5.0.4 on 2024-04-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Nebulosa', 'NEBULOSA'), ('Estrela', 'ESTRELA'), ('Galáxia', 'GALÁXIA'), ('Planeta', 'PLANETA')], default='', max_length=150),
        ),
    ]
